[project]
name = "gmm-divergence"
version = "0.0.1a9"
description = "Utilities for estimating divergences between Gaussian mixture models."
readme = "README.md"
authors = [
    { name = "David Axelsson", email = "david.axelsson@liu.se" }
]
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
keywords = ["divergence", "gaussian-mixture-model", "gmm", "kl-divergence", "numpy"]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
dependencies = [
    "numpy>=1.26",
    "scikit-learn>=1.7.2",
    "scipy>=1.15.3",
    "typing-extensions>=4.13.2",
]

[project.urls]
"Repository" = "https://github.com/davaxe/gmm-divergence"
"Documentation" = "https://davaxe.github.io/gmm-divergence/"

[dependency-groups]
build = [
    "build>=1.5.0",
    "twine>=6.2.0",
]
docs = [
    "mkdocstrings[python]>=1.0.4",
    "zensical>=0.0.43",
]
test = [
    "pytest>=8.3.5",
    "pytest-benchmark>=5.2.3",
]
lint = [
    "ruff>=0.15.12",
]
typecheck = [
    "scipy-stubs>=1.15.3.0",
    "basedpyright>=1.0.0",
    "scikit-learn-stubs>=0.0.3",
]
example = [
]
dev = [
    { include-group = "build" },
    { include-group = "docs" },
    { include-group = "lint" },
    { include-group = "test" },
    { include-group = "typecheck" },
    { include-group = "example" },
]

[build-system]
requires = ["uv_build>=0.11.16,<0.13.0"]
build-backend = "uv_build"

[tool.ruff]
line-length = 100
preview = true

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "incorrect-blank-line-before-class",
    "multi-line-summary-second-line",
    "missing-trailing-comma",
    "magic-value-comparison",
    "docstring-missing-returns",
    "docstring-missing-exception",
    "raise-vanilla-args",
    "undocumented-public-module",
    "too-many-public-methods",
    "missing-todo-author",
    "missing-todo-link",
    "too-many-arguments",
    "too-many-positional-arguments",
    "too-many-locals",
    "docstring-missing-yields",
    "missing-copyright-notice",
    "undocumented-public-package",
    "missing-todo-description",
    "unnecessary-dunder-call",
    "undocumented-public-class",
]
pydocstyle = { convention = "numpy" }

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = ["D", "implicit-namespace-package", "assert", "import-private-name"]
"examples/**/*.py" = ["D", "implicit-namespace-package", "assert", "import-private-name"]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.ruff.format]
quote-style = "double"
skip-magic-trailing-comma = true

[tool.ruff.lint.isort]
split-on-trailing-comma = false

[tool.basedpyright]
# pythonVersion = "3.10"
pythonPlatform = "All"
typeCheckingMode = "recommended"
include = ["src", "tests"]
reportAny = false
reportUnknownMemberType = false
